### ISSUE TITLE
Spring Boot OAuth2

### ISSUE THREAD

**Issue by glebrodionov** [rjaros/kvision#160]
First of all I would like to say that this project seems very promising and can be used by our company's internal tools team. 

Thank you for your hard work on integrations and documentation.

We use OAuth2 (Keycloak) in our company for authentication. I tried `template-fullstack-spring-boot` example and added simple oauth security configuration:

1. `implementation("org.springframework.boot:spring-boot-starter-oauth2-client")`
2. simple application.yml Github configuration:
```yaml
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: client_id
            clientSecret: client_secret
```
3. 
``` kotlin
@Bean    
fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        return http
            .csrf().disable()
            .authorizeExchange().anyExchange().authenticated().and()
            .oauth2Login()
            .and().build()
    }
```

But after I launch app I am getting:
`jquery.js?0110:10099 GET http://localhost:3000/login 404 (Not Found)`

Should I somehow provide implementation for /login on UI? What is a correct way to handle such situation?

Thanks in advance!
